### ISSUE TITLE
tkinter error and registration error

### ISSUE THREAD

**Issue by vrundorion** [shubhamkumar27/Face_recognition_based_attendance_system#7]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\vrund\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\vrund\AppData\Local\Temp\Temp3_Face_recognition_based_attendance_system-master.zip\Face_recognition_based_attendance_system-master\main.py", line 167, in TakeImages
    Id = (txt.get())
  File "C:\Users\vrund\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2679, in get
    return self.tk.call(self._w, 'get')
_tkinter.TclError: invalid command name ".!frame2.!entry"

please help 
when I click on take image error occurs  that some files are missing

**Comment by Kaustubh-3105** [comment]
Step1- First of all added the “**global txt, txt2”** to make variables global in **clear(),TakeImages(),clear2()** functions.
Step 2- (Important) Then changed the **path directory** to that of the project before running to ensure that all files will be available .
Step 3 - Then made certain GUI changes to take the data properly for registration purpose.
