### ISSUE TITLE
attribute error in project

### ISSUE THREAD

**Issue by yash463github** [shubhamkumar27/Face_recognition_based_attendance_system#9]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Yash Dhumal\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Yash Dhumal\Desktop\FRBAS\main.py", line 259, in TrackImages
    recognizer = cv2.face.LBPHFaceRecognizer_create()  # cv2.createLBPHFaceRecognizer()
                 ^^^^^^^^
AttributeError: module 'cv2' has no attribute 'face'

i am getting this error and it is not taking attendance , pls help me fix this error
![pbl issue](https://user-images.githubusercontent.com/132649136/236611423-ea0b8a2c-0138-4b56-b7bf-c70eb9aff454.jpg)

**Comment by Akshat03-ai** [comment]
same error on my pc, did u find the solution though??

**Comment by yash463github** [comment]
> same error on my pc, did u find the solution though??

Nope 👎... It is not running another device also
